default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_sid: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_auth_token: <%= ENV["SECRET_KEY_BASE"] %>

development:
  <<: *default

production:
  <<: *default
